# Netlify full-stack deployment for HENGEBUKEN
[build]
  command = "npm ci && vite build"
  publish = "dist/public"
  functions = "functions"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

# Route specific API calls to Netlify Functions
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/members/*"
  to = "/.netlify/functions/members"
  status = 200

[[redirects]]
  from = "/api/spain-presence/*"
  to = "/.netlify/functions/spain-presence"
  status = 200

[[redirects]]
  from = "/api/tee-times/*"
  to = "/.netlify/functions/tee-times"
  status = 200

[[redirects]]
  from = "/api/absences/*"
  to = "/.netlify/functions/absences"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# Fallback for other API calls
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for all other routes (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true